#Script that examines the correlation between length of word and quality of search term 
# from Home Depot Kaggle data set 

# Upload the information ... 
train <- read.csv("~/train.csv", header = TRUE)
summary(train)

# Create column that has length of row's search term:
train$search_term = as.character(train$search_term)
train$search_length = nchar(train$search_term)

# Run regression to see how search_length correlates with relevance 
model1 <- lm("relevance ~ search_length", train)

#Check correlation between number of words and relevance ----

train$search_words <- sapply(gregexpr("\\W+", train$search_term), length) + 1
hist(train$search_words, breaks = 20)

# Run regression. We may have to remove outliers ... but yeah: 
model2 <- lm("relevance ~ search_words", train)

trainw <- train[train$search_words < 10,]
model3 <- lm("relevance ~ search_words", trainw)

# Create list of stop words ----
{
  stopwords = c("a" ,
                "able" ,
                "about" ,
                "above" ,
                "abst" ,
                "accordance" ,
                "according" ,
                "accordingly" ,
                "across" ,
                "act" ,
                "actually" ,
                "added" ,
                "adj" ,
                "affected" ,
                "affecting" ,
                "affects" ,
                "after" ,
                "afterwards" ,
                "again" ,
                "against" ,
                "ah" ,
                "all" ,
                "almost" ,
                "alone" ,
                "along" ,
                "already" ,
                "also" ,
                "although" ,
                "always" ,
                "am" ,
                "among" ,
                "amongst" ,
                "an" ,
                "and" ,
                "announce" ,
                "another" ,
                "any" ,
                "anybody" ,
                "anyhow" ,
                "anymore" ,
                "anyone" ,
                "anything" ,
                "anyway" ,
                "anyways" ,
                "anywhere" ,
                "apparently" ,
                "approximately" ,
                "are" ,
                "aren" ,
                "arent" ,
                "arise" ,
                "around" ,
                "as" ,
                "aside" ,
                "ask" ,
                "asking" ,
                "at" ,
                "auth" ,
                "available" ,
                "away" ,
                "awfully" ,
                "b" ,
                "back" ,
                "be" ,
                "became" ,
                "because" ,
                "become" ,
                "becomes" ,
                "becoming" ,
                "been" ,
                "before" ,
                "beforehand" ,
                "begin" ,
                "beginning" ,
                "beginnings" ,
                "begins" ,
                "behind" ,
                "being" ,
                "believe" ,
                "below" ,
                "beside" ,
                "besides" ,
                "between" ,
                "beyond" ,
                "biol" ,
                "both" ,
                "brief" ,
                "briefly" ,
                "but" ,
                "by" ,
                "c" ,
                "ca" ,
                "came" ,
                "can" ,
                "cannot" ,
                "can't" ,
                "cause" ,
                "causes" ,
                "certain" ,
                "certainly" ,
                "co" ,
                "com" ,
                "come" ,
                "comes" ,
                "contain" ,
                "containing" ,
                "contains" ,
                "could" ,
                "couldnt" ,
                "d" ,
                "date" ,
                "did" ,
                "didn't" ,
                "different" ,
                "do" ,
                "does" ,
                "doesn't" ,
                "doing" ,
                "done" ,
                "don't" ,
                "down" ,
                "downwards" ,
                "due" ,
                "during" ,
                "e" ,
                "each" ,
                "ed" ,
                "edu" ,
                "effect" ,
                "eg" ,
                "eight" ,
                "eighty" ,
                "either" ,
                "else" ,
                "elsewhere" ,
                "end" ,
                "ending" ,
                "enough" ,
                "especially" ,
                "et" ,
                "et-al" ,
                "etc" ,
                "even" ,
                "ever" ,
                "every" ,
                "everybody" ,
                "everyone" ,
                "everything" ,
                "everywhere" ,
                "ex" ,
                "except" ,
                "f" ,
                "far" ,
                "few" ,
                "ff" ,
                "fifth" ,
                "first" ,
                "five" ,
                "fix" ,
                "followed" ,
                "following" ,
                "follows" ,
                "for" ,
                "former" ,
                "formerly" ,
                "forth" ,
                "found" ,
                "four" ,
                "from" ,
                "further" ,
                "furthermore" ,
                "g" ,
                "gave" ,
                "get" ,
                "gets" ,
                "getting" ,
                "give" ,
                "given" ,
                "gives" ,
                "giving" ,
                "go" ,
                "goes" ,
                "gone" ,
                "got" ,
                "gotten" ,
                "h" ,
                "had" ,
                "happens" ,
                "hardly" ,
                "has" ,
                "hasn't" ,
                "have" ,
                "haven't" ,
                "having" ,
                "he" ,
                "hed" ,
                "hence" ,
                "her" ,
                "here" ,
                "hereafter" ,
                "hereby" ,
                "herein" ,
                "heres" ,
                "hereupon" ,
                "hers" ,
                "herself" ,
                "hes" ,
                "hi" ,
                "hid" ,
                "him" ,
                "himself" ,
                "his" ,
                "hither" ,
                "home" ,
                "how" ,
                "howbeit" ,
                "however" ,
                "hundred" ,
                "i" ,
                "id" ,
                "ie" ,
                "if" ,
                "i'll" ,
                "im" ,
                "immediate" ,
                "immediately" ,
                "importance" ,
                "important" ,
                "in" ,
                "inc" ,
                "indeed" ,
                "index" ,
                "information" ,
                "instead" ,
                "into" ,
                "invention" ,
                "inward" ,
                "is" ,
                "isn't" ,
                "it" ,
                "itd" ,
                "it'll" ,
                "its" ,
                "itself" ,
                "i've" ,
                "j" ,
                "just" ,
                "k" ,
                "keep" ,
                "keeps" ,
                "kept" ,
                "kg" ,
                "km" ,
                "know" ,
                "known" ,
                "knows" ,
                "l" ,
                "largely" ,
                "last" ,
                "lately" ,
                "later" ,
                "latter" ,
                "latterly" ,
                "least" ,
                "less" ,
                "lest" ,
                "let" ,
                "lets" ,
                "like" ,
                "liked" ,
                "likely" ,
                "line" ,
                "little" ,
                "'ll" ,
                "look" ,
                "looking" ,
                "looks" ,
                "ltd" ,
                "m" ,
                "made" ,
                "mainly" ,
                "make" ,
                "makes" ,
                "many" ,
                "may" ,
                "maybe" ,
                "me" ,
                "mean" ,
                "means" ,
                "meantime" ,
                "meanwhile" ,
                "merely" ,
                "mg" ,
                "might" ,
                "million" ,
                "miss" ,
                "ml" ,
                "more" ,
                "moreover" ,
                "most" ,
                "mostly" ,
                "mr" ,
                "mrs" ,
                "much" ,
                "mug" ,
                "must" ,
                "my" ,
                "myself" ,
                "n" ,
                "na" ,
                "name" ,
                "namely" ,
                "nay" ,
                "nd" ,
                "near" ,
                "nearly" ,
                "necessarily" ,
                "necessary" ,
                "need" ,
                "needs" ,
                "neither" ,
                "never" ,
                "nevertheless" ,
                "new" ,
                "next" ,
                "nine" ,
                "ninety" ,
                "no" ,
                "nobody" ,
                "non" ,
                "none" ,
                "nonetheless" ,
                "noone" ,
                "nor" ,
                "normally" ,
                "nos" ,
                "not" ,
                "noted" ,
                "nothing" ,
                "now" ,
                "nowhere" ,
                "o" ,
                "obtain" ,
                "obtained" ,
                "obviously" ,
                "of" ,
                "off" ,
                "often" ,
                "oh" ,
                "ok" ,
                "okay" ,
                "old" ,
                "omitted" ,
                "on" ,
                "once" ,
                "one" ,
                "ones" ,
                "only" ,
                "onto" ,
                "or" ,
                "ord" ,
                "other" ,
                "others" ,
                "otherwise" ,
                "ought" ,
                "our" ,
                "ours" ,
                "ourselves" ,
                "out" ,
                "outside" ,
                "over" ,
                "overall" ,
                "owing" ,
                "own" ,
                "p" ,
                "page" ,
                "pages" ,
                "part" ,
                "particular" ,
                "particularly" ,
                "past" ,
                "per" ,
                "perhaps" ,
                "placed" ,
                "please" ,
                "plus" ,
                "poorly" ,
                "possible" ,
                "possibly" ,
                "potentially" ,
                "pp" ,
                "predominantly" ,
                "present" ,
                "previously" ,
                "primarily" ,
                "probably" ,
                "promptly" ,
                "proud" ,
                "provides" ,
                "put" ,
                "q" ,
                "que" ,
                "quickly" ,
                "quite" ,
                "qv" ,
                "r" ,
                "ran" ,
                "rather" ,
                "rd" ,
                "re" ,
                "readily" ,
                "really" ,
                "recent" ,
                "recently" ,
                "ref" ,
                "refs" ,
                "regarding" ,
                "regardless" ,
                "regards" ,
                "related" ,
                "relatively" ,
                "research" ,
                "respectively" ,
                "resulted" ,
                "resulting" ,
                "results" ,
                "right" ,
                "run" ,
                "s" ,
                "said" ,
                "same" ,
                "saw" ,
                "say" ,
                "saying" ,
                "says" ,
                "sec" ,
                "section" ,
                "see" ,
                "seeing" ,
                "seem" ,
                "seemed" ,
                "seeming" ,
                "seems" ,
                "seen" ,
                "self" ,
                "selves" ,
                "sent" ,
                "seven" ,
                "several" ,
                "shall" ,
                "she" ,
                "shed" ,
                "she'll" ,
                "shes" ,
                "should" ,
                "shouldn't" ,
                "show" ,
                "showed" ,
                "shown" ,
                "showns" ,
                "shows" ,
                "significant" ,
                "significantly" ,
                "similar" ,
                "similarly" ,
                "since" ,
                "six" ,
                "slightly" ,
                "so" ,
                "some" ,
                "somebody" ,
                "somehow" ,
                "someone" ,
                "somethan" ,
                "something" ,
                "sometime" ,
                "sometimes" ,
                "somewhat" ,
                "somewhere" ,
                "soon" ,
                "sorry" ,
                "specifically" ,
                "specified" ,
                "specify" ,
                "specifying" ,
                "still" ,
                "stop" ,
                "strongly" ,
                "sub" ,
                "substantially" ,
                "successfully" ,
                "such" ,
                "sufficiently" ,
                "suggest" ,
                "sup" ,
                "sure" ,
                "t" ,
                "take" ,
                "taken" ,
                "taking" ,
                "tell" ,
                "tends" ,
                "th" ,
                "than" ,
                "thank" ,
                "thanks" ,
                "thanx" ,
                "that" ,
                "that'll" ,
                "thats" ,
                "that've" ,
                "the" ,
                "their" ,
                "theirs" ,
                "them" ,
                "themselves" ,
                "then" ,
                "thence" ,
                "there" ,
                "thereafter" ,
                "thereby" ,
                "thered" ,
                "therefore" ,
                "therein" ,
                "there'll" ,
                "thereof" ,
                "therere" ,
                "theres" ,
                "thereto" ,
                "thereupon" ,
                "there've" ,
                "these" ,
                "they" ,
                "theyd" ,
                "they'll" ,
                "theyre" ,
                "they've" ,
                "think" ,
                "this" ,
                "those" ,
                "thou" ,
                "though" ,
                "thoughh" ,
                "thousand" ,
                "throug" ,
                "through" ,
                "throughout" ,
                "thru" ,
                "thus" ,
                "til" ,
                "tip" ,
                "to" ,
                "together" ,
                "too" ,
                "took" ,
                "toward" ,
                "towards" ,
                "tried" ,
                "tries" ,
                "truly" ,
                "try" ,
                "trying" ,
                "ts" ,
                "twice" ,
                "two" ,
                "u" ,
                "un" ,
                "under" ,
                "unfortunately" ,
                "unless" ,
                "unlike" ,
                "unlikely" ,
                "until" ,
                "unto" ,
                "up" ,
                "upon" ,
                "ups" ,
                "us" ,
                "use" ,
                "used" ,
                "useful" ,
                "usefully" ,
                "usefulness" ,
                "uses" ,
                "using" ,
                "usually" ,
                "v" ,
                "value" ,
                "various" ,
                "'ve" ,
                "very" ,
                "via" ,
                "viz" ,
                "vol" ,
                "vols" ,
                "vs" ,
                "w" ,
                "want" ,
                "wants" ,
                "was" ,
                "wasnt" ,
                "way" ,
                "we" ,
                "wed" ,
                "welcome" ,
                "we'll" ,
                "went" ,
                "were" ,
                "werent" ,
                "we've" ,
                "what" ,
                "whatever" ,
                "what'll" ,
                "whats" ,
                "when" ,
                "whence" ,
                "whenever" ,
                "where" ,
                "whereafter" ,
                "whereas" ,
                "whereby" ,
                "wherein" ,
                "wheres" ,
                "whereupon" ,
                "wherever" ,
                "whether" ,
                "which" ,
                "while" ,
                "whim" ,
                "whither" ,
                "who" ,
                "whod" ,
                "whoever" ,
                "whole" ,
                "who'll" ,
                "whom" ,
                "whomever" ,
                "whos" ,
                "whose" ,
                "why" ,
                "widely" ,
                "willing" ,
                "wish" ,
                "with" ,
                "within" ,
                "without" ,
                "wont" ,
                "words" ,
                "world" ,
                "would" ,
                "wouldnt" ,
                "www" ,
                "x" ,
                "y" ,
                "yes" ,
                "yet" ,
                "you" ,
                "youd" ,
                "you'll" ,
                "your" ,
                "youre" ,
                "yours" ,
                "yourself" ,
                "yourselves" ,
                "you've" ,
                "z" ,
                "zero" 
  )
}

# Filter out words that are stopwords: 
library(tm)
for(i in 1:nrow(train)){
  train$search_term[i] = removeWords(train$search_term[i], stopwords)
}

# Let's take look at how words lengths were affected 
train$search_words <- sapply(gregexpr("\\W+", train$search_term), length) + 1
hist(train$search_words, breaks = 10)

#
model4 <- lm("relevance ~ search_words", train)

# Earlier, when I did visuals ... ----

hist(train$search_length, breaks = 40)

#Order the dataset by character length of search term: 
library(data.table)
train <- data.table(train)
train <- train[order(search_length)] 


# Visualize search term relevance by bucket: 
library(gtools)
train$tcut <- quantcut(train$search_length, q =10)
avg <- train[,.(avg_s = mean(relevance)), by = tcut]
plot(avg$avg_s, main = "Average relevance per search_length decile", 
     ylab = "Relevance Score", xlab = "search_length deciles")
lines(avg$avg_s)

# Find intersection between product_title and search_term ----

#First, stem the words 
install.packages("Rstem")
library(Rstem)

train$search_term <- wordStem(train$search_term)
train$product_title <- wordStem(as.character(train$product_title))

# Create column that tracks number of insecting words between the two columns 
for(i in 1:nrow(train)){
  a_split <- unlist(strsplit(train$product_title[i], split=" "))
  b_split <- unlist(strsplit(train$search_term[i], split =" "))
  train$int_length[i] <- length(intersect(a_split, b_split))
}

model5 <- lm("relevance ~ int_length", train)

#Create categorical variable if a intersecting word or not 
for(i in 1:nrow(train)){
  if(train$int_length[i] >0){
    train$intersect[i] = 1
  }
  else{
    train$intersect[i] = 0
  }
}

#Create data.table 
train <- data.table(train)

#Get relevance rates by intersection or not 
avg_r <- train[,.(avg_s = mean(relevance)), by = intersect]

